# Generated by Django 4.2.2 on 2023-07-26 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribeduser',
            name='user',
        ),
    ]
