# Generated by Django 4.2.2 on 2023-07-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0002_customuser_is_superuser'),
        ('SubjectSelection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='enrolled_user',
            field=models.ManyToManyField(blank=True, related_name='enrolled_subjects', to='authentication_app.customuser'),
        ),
        migrations.AddField(
            model_name='subjects',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
