# Generated by Django 4.2.2 on 2023-07-03 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0002_customuser_is_superuser'),
        ('SubjectSelection', '0003_remove_subjects_enrolled_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SubjectSelection.subjects')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication_app.customuser')),
            ],
        ),
    ]
