# Generated by Django 4.2.2 on 2023-07-28 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SubjectSelection', '0006_remove_lesson_video_url_alter_enrollment_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='subject',
        ),
        migrations.AddField(
            model_name='lesson',
            name='unit',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, to='SubjectSelection.unit'),
        ),
    ]
