# Generated by Django 4.2.2 on 2023-07-29 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SubjectSelection', '0007_remove_lesson_subject_lesson_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonvideo',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SubjectSelection.lesson'),
        ),
    ]
