# Generated by Django 4.2.2 on 2023-07-29 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SubjectSelection', '0009_alter_lessonvideo_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonvideo',
            name='lesson',
        ),
    ]
