# Generated by Django 4.2.2 on 2023-07-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubjectSelection', '0010_remove_lessonvideo_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyLessonVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('video_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
