# Generated by Django 4.2.2 on 2023-08-04 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProgressTrackkingApp', '0001_initial'),
        ('SubjectSelection', '0012_lessonvideo_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='completionStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='progress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProgressTrackkingApp.progresstracker'),
        ),
        migrations.AddField(
            model_name='unit',
            name='completionStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='progress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProgressTrackkingApp.progresstracker'),
        ),
    ]
