# Generated by Django 4.2.2 on 2023-08-05 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SubjectSelection', '0013_lesson_completionstatus_lesson_progress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='completionStatus',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='completionStatus',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='progress',
        ),
    ]
