# Generated by Django 4.2.2 on 2023-07-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
