# Generated by Django 4.2.2 on 2023-07-30 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tests', '0002_option_title_question_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='title',
        ),
    ]
