# Generated by Django 4.2.2 on 2023-07-30 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tests', '0003_remove_test_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
