# Generated by Django 4.2.2 on 2023-07-31 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tests', '0004_test_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='skipped',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
